adding install script moving some files around a bit

diff --git a/install b/install
--- a/install
+++ b/install
@@ -31,7 +31,6 @@ set -u
 
 version=1.6.1
 auto_completion=
-key_bindings=
 update_config=2
 binary_arch=
 shells="bash zsh"
@@ -72,15 +71,6 @@ for opt in "$@"; do
       key_bindings=1
       update_config=1
       ;;
-    --xdg)
-      prefix='"${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf'
-      prefix_expand=${XDG_CONFIG_HOME:-$HOME/.config}/fzf/fzf
-      mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/fzf"
-      ;;
-    --key-bindings)    key_bindings=1    ;;
-    --no-key-bindings) key_bindings=0    ;;
-    --completion)      auto_completion=1 ;;
-    --no-completion)   auto_completion=0 ;;
     --update-rc)       update_config=1   ;;
     --no-update-rc)    update_config=0   ;;
     --32)              binary_arch=386   ;;
@@ -98,8 +88,8 @@ for opt in "$@"; do
 done
 
 cd "$(dirname "${BASH_SOURCE[0]}")"
-fzf_base=$(pwd)
-fzf_base_esc=$(printf %q "$fzf_base")
+loki_shell_base=$(pwd)
+loki_shell_base_esc=$(printf %q "$loki_shell_base")
 
 ask() {
   while true; do
@@ -113,17 +103,26 @@ ask() {
   done
 }
 
+prompt() {
+  read -p "$1 (press any key to continue) " -r
+}
+
+prompt_string() {
+  read -p "$1 (http://localhost:4100) " -r
+  REPLY=${REPLY:-"$2"}
+  echo $REPLY
+}
+
 check_binary() {
-  echo -n "  - Checking fzf executable ... "
+  echo -n "  - Checking ${1} executable ... "
   local output
-  output=$("$fzf_base"/bin/fzf --version 2>&1)
+  output=$("$loki_shell_base"/bin/${1} --version 2>&1)
   if [ $? -ne 0 ]; then
     echo "Error: $output"
     binary_error="Invalid binary"
   else
-    output=${output/ */}
-    if [ "$version" != "$output" ]; then
-      echo "$output != $version"
+    if [[ $output != *"$version"* ]]; then
+      echo "output did not contain correct version $version: $output"
       binary_error="Invalid version"
     else
       echo "$output"
@@ -131,17 +130,7 @@ check_binary() {
       return 0
     fi
   fi
-  rm -f "$fzf_base"/bin/fzf
-  return 1
-}
-
-link_fzf_in_path() {
-  if which_fzf="$(command -v fzf)"; then
-    echo "  - Found in \$PATH"
-    echo "  - Creating symlink: bin/fzf -> $which_fzf"
-    (cd "$fzf_base"/bin && rm -f fzf && ln -sf "$which_fzf" fzf)
-    check_binary && return
-  fi
+  rm -f "$loki_shell_base"/bin/${1}
   return 1
 }
 
@@ -150,7 +139,7 @@ try_curl() {
   if [[ $1 =~ tgz$ ]]; then
     curl -fL $1 | tar -xzf -
   else
-    local temp=${TMPDIR:-/tmp}/fzf.zip
+    local temp=${TMPDIR:-/tmp}/temp.zip
     curl -fLo "$temp" $1 && unzip -o "$temp" && rm -f "$temp"
   fi
 }
@@ -160,30 +149,28 @@ try_wget() {
   if [[ $1 =~ tgz$ ]]; then
     wget -O - $1 | tar -xzf -
   else
-    local temp=${TMPDIR:-/tmp}/fzf.zip
+    local temp=${TMPDIR:-/tmp}/${1}.zip
     wget -O "$temp" $1 && unzip -o "$temp" && rm -f "$temp"
   fi
 }
 
 download() {
-  echo "Downloading bin/fzf ..."
-  if [[ ! "$version" =~ alpha ]]; then
-    if [ -x "$fzf_base"/bin/fzf ]; then
-      echo "  - Already exists"
-      check_binary && return
-    fi
-    link_fzf_in_path && return
+  echo "Downloading ${1}"
+
+  if [ -x "$loki_shell_base"/bin/"${1}" ]; then
+    echo "  - Already exists"
+    check_binary ${1} && return
   fi
-  mkdir -p "$fzf_base"/bin && cd "$fzf_base"/bin
+
+  mkdir -p "$loki_shell_base"/bin && cd "$loki_shell_base"/bin
   if [ $? -ne 0 ]; then
     binary_error="Failed to create bin directory"
     return
   fi
 
   local url
-  [[ "$version" =~ alpha ]] &&
-    url=https://github.com/junegunn/fzf-bin/releases/download/alpha/${1} ||
-    url=https://github.com/junegunn/fzf-bin/releases/download/$version/${1}
+  url=https://github.com/grafana/loki/releases/download/v$version/${2}
+
   set -o pipefail
   if ! (try_curl $url || try_wget $url); then
     set +o pipefail
@@ -192,12 +179,14 @@ download() {
   fi
   set +o pipefail
 
-  if [ ! -f fzf ]; then
+  mv *${1}* ${1}
+
+  if [ ! -f ${1} ]; then
     binary_error="Failed to download ${1}"
     return
   fi
 
-  chmod +x fzf && check_binary
+  chmod +x ${1} && check_binary ${1}
 }
 
 # Try to download binary executable
@@ -205,54 +194,38 @@ archi=$(uname -sm)
 binary_available=1
 binary_error=""
 case "$archi" in
-  Darwin\ *64)   download fzf-$version-darwin_${binary_arch:-amd64}.tgz  ;;
-  Darwin\ *86)   download fzf-$version-darwin_${binary_arch:-386}.tgz    ;;
-  Linux\ armv5*) download fzf-$version-linux_${binary_arch:-arm5}.tgz    ;;
-  Linux\ armv6*) download fzf-$version-linux_${binary_arch:-arm6}.tgz    ;;
-  Linux\ armv7*) download fzf-$version-linux_${binary_arch:-arm7}.tgz    ;;
-  Linux\ armv8*) download fzf-$version-linux_${binary_arch:-arm8}.tgz    ;;
-  Linux\ aarch64*) download fzf-$version-linux_${binary_arch:-arm8}.tgz  ;;
-  Linux\ *64)    download fzf-$version-linux_${binary_arch:-amd64}.tgz   ;;
-  Linux\ *86)    download fzf-$version-linux_${binary_arch:-386}.tgz     ;;
-  FreeBSD\ *64)  download fzf-$version-freebsd_${binary_arch:-amd64}.tgz ;;
-  FreeBSD\ *86)  download fzf-$version-freebsd_${binary_arch:-386}.tgz   ;;
-  OpenBSD\ *64)  download fzf-$version-openbsd_${binary_arch:-amd64}.tgz ;;
-  OpenBSD\ *86)  download fzf-$version-openbsd_${binary_arch:-386}.tgz   ;;
-  CYGWIN*\ *64)  download fzf-$version-windows_${binary_arch:-amd64}.zip ;;
-  MINGW*\ *86)   download fzf-$version-windows_${binary_arch:-386}.zip   ;;
-  MINGW*\ *64)   download fzf-$version-windows_${binary_arch:-amd64}.zip ;;
-  MSYS*\ *86)    download fzf-$version-windows_${binary_arch:-386}.zip   ;;
-  MSYS*\ *64)    download fzf-$version-windows_${binary_arch:-amd64}.zip ;;
-  Windows*\ *86) download fzf-$version-windows_${binary_arch:-386}.zip   ;;
-  Windows*\ *64) download fzf-$version-windows_${binary_arch:-amd64}.zip ;;
+  Darwin\ *64)
+    download promtail promtail-darwin-${binary_arch:-amd64}.zip
+    download logcli logcli-darwin-${binary_arch:-amd64}.zip
+    download loki loki-darwin-${binary_arch:-amd64}.zip
+    ;;
+  Linux\ armv7*)
+    download promtail promtail-linux-${binary_arch:-arm}.zip
+    download logcli logcli-linux-${binary_arch:-arm}.zip
+    download loki loki-linux-${binary_arch:-arm}.zip
+    ;;
+  Linux\ armv8*)
+    download promtail promtail-linux-${binary_arch:-arm64}.zip
+    download logcli logcli-linux-${binary_arch:-arm64}.zip
+    download loki loki-linux-${binary_arch:-arm64}.zip
+    ;;
+  Linux\ aarch64*)
+    download promtail promtail-linux-${binary_arch:-arm64}.zip
+    download logcli logcli-linux-${binary_arch:-arm64}.zip
+    download loki loki-linux-${binary_arch:-arm64}.zip
+    ;;
+  Linux\ *64)
+    download promtail promtail-linux-${binary_arch:-amd64}.zip
+    download logcli logcli-linux-${binary_arch:-amd64}.zip
+    download loki loki-linux-${binary_arch:-amd64}.zip
+    ;;
+  OpenBSD\ *64)
+    download promtail promtail-freebsd-${binary_arch:-amd64}.zip
+    download logcli logcli-freebsd-${binary_arch:-amd64}.zip
+    download loki loki-freebsd-${binary_arch:-amd64}.zip
+    ;;
   *)             binary_available=0 binary_error=1 ;;
 esac
-
-cd "$fzf_base"
-if [ -n "$binary_error" ]; then
-  if [ $binary_available -eq 0 ]; then
-    echo "No prebuilt binary for $archi ..."
-  else
-    echo "  - $binary_error !!!"
-  fi
-  if command -v go > /dev/null; then
-    echo -n "Building binary (go get -u github.com/junegunn/fzf) ... "
-    if [ -z "${GOPATH-}" ]; then
-      export GOPATH="${TMPDIR:-/tmp}/fzf-gopath"
-      mkdir -p "$GOPATH"
-    fi
-    if go get -u github.com/junegunn/fzf; then
-      echo "OK"
-      cp "$GOPATH/bin/fzf" "$fzf_base/bin/"
-    else
-      echo "Failed to build binary. Installation failed."
-      exit 1
-    fi
-  else
-    echo "go executable not found. Installation failed."
-    exit 1
-  fi
-fi
 
 [[ "$*" =~ "--bin" ]] && exit 0
 
@@ -265,79 +238,6 @@ done
 if [[ ${#shells} -lt 3 ]]; then
   echo "No shell configuration to be updated."
   exit 0
-fi
-
-# Auto-completion
-if [ -z "$auto_completion" ]; then
-  ask "Do you want to enable fuzzy auto-completion?"
-  auto_completion=$?
-fi
-
-# Key-bindings
-if [ -z "$key_bindings" ]; then
-  ask "Do you want to enable key bindings?"
-  key_bindings=$?
-fi
-
-echo
-for shell in $shells; do
-  [[ "$shell" = fish ]] && continue
-  src=${prefix_expand}.${shell}
-  echo -n "Generate $src ... "
-
-  fzf_completion="[[ \$- == *i* ]] && source \"$fzf_base/shell/completion.${shell}\" 2> /dev/null"
-  if [ $auto_completion -eq 0 ]; then
-    fzf_completion="# $fzf_completion"
-  fi
-
-  fzf_key_bindings="source \"$fzf_base/shell/key-bindings.${shell}\""
-  if [ $key_bindings -eq 0 ]; then
-    fzf_key_bindings="# $fzf_key_bindings"
-  fi
-
-  cat > "$src" << EOF
-# Setup fzf
-# ---------
-if [[ ! "\$PATH" == *$fzf_base_esc/bin* ]]; then
-  export PATH="\${PATH:+\${PATH}:}$fzf_base/bin"
-fi
-
-# Auto-completion
-# ---------------
-$fzf_completion
-
-# Key bindings
-# ------------
-$fzf_key_bindings
-EOF
-  echo "OK"
-done
-
-# fish
-if [[ "$shells" =~ fish ]]; then
-  echo -n "Update fish_user_paths ... "
-  fish << EOF
-  echo \$fish_user_paths | \grep "$fzf_base"/bin > /dev/null
-  or set --universal fish_user_paths \$fish_user_paths "$fzf_base"/bin
-EOF
-  [ $? -eq 0 ] && echo "OK" || echo "Failed"
-
-  mkdir -p "${fish_dir}/functions"
-  if [ -e "${fish_dir}/functions/fzf.fish" ]; then
-    echo -n "Remove unnecessary ${fish_dir}/functions/fzf.fish ... "
-    rm -f "${fish_dir}/functions/fzf.fish" && echo "OK" || echo "Failed"
-  fi
-
-  fish_binding="${fish_dir}/functions/fzf_key_bindings.fish"
-  if [ $key_bindings -ne 0 ]; then
-    echo -n "Symlink $fish_binding ... "
-    ln -sf "$fzf_base/shell/key-bindings.fish" \
-           "$fish_binding" && echo "OK" || echo "Failed"
-  else
-    echo -n "Removing $fish_binding ... "
-    rm -f "$fish_binding"
-    echo "OK"
-  fi
 fi
 
 append_line() {
@@ -374,40 +274,90 @@ append_line() {
   set +e
 }
 
-create_file() {
-  local file="$1"
-  shift
-  echo "Create $file:"
-  for line in "$@"; do
-    echo "    $line"
-    echo "$line" >> "$file"
-  done
+# Install Loki
+sudo apt-get update
+
+echo
+ask "Do you want to install Loki?"
+install_loki=$?
+
+if [ $install_loki -eq 1 ]; then
+  ## Ask docker or binary
   echo
-}
+  ask "[y] to run Loki in Docker, [n] to run Loki as a binary"
+  docker=$?
+  if [ $docker -eq 1 ]; then
+    if [ -x "$loki_shell_base"/config/loki-docker-config.yaml ]; then
+      prompt "Existing config file found at $loki_shell_base/.loki-shell/config/loki-docker-config.yaml\nFile will not be modified\n"
+    else
+      cp cfg-template/loki-docker-local-config.yaml config/loki-docker-config.yaml
+    fi
+
+    docker inspect loki-shell | grep -q "grafana/loki:$version"
+    if [ $? -ne 0 ]; then
+      docker stop loki-shell || true
+      docker rm loki-shell || true
+      docker run -d --restart=unless-stopped --name=loki-shell --mount type=bind,source=$loki_shell_base/.loki-shell/config/loki-docker-config.yaml,target=/etc/loki/local-config.yaml --mount type=bind,source=$loki_shell_base/.loki-shell/data,target=/loki -p 4100:4100 grafana/loki:$version
+    else
+      echo "loki-shell docker image already running at correct version"
+    fi
+  else
+    if [ -x "$loki_shell_base"/config/loki-binary-confg.yaml ]; then
+      prompt "Existing config file found at $loki_shell_base/.loki-shell/config/loki-binary-config.yaml\nFile will not be modified\n"
+    else
+      cp cfg-template/loki-local-config.yaml config/loki-binary-config.yaml
+      sed -i "s|FIXME|$loki_shell_base|g" config/loki-binary-config.yaml
+    fi
+    echo
+    ask "Run Loki with systemd?"
+    systemd=$?
+    if [ $systemd -eq 1 ]; then
+      cp cfg-template/loki.service config/loki.service
+      sed -i "s|FIXME|$loki_shell_base|g" config/loki.service
+      sed -i "s|USER|$USER|g" config/loki.service
+      echo
+      ask "Installing the systemd service requires root permissions.\n[y] to run these commands with sudo [n] to print out the commands and you can run them yourself."
+      run_sudo_cmds=$?
+      if [ $run_sudo_cmds -eq 1 ]; then
+        sudo cp $loki_shell_base/config/loki.service /etc/systemd/system/loki.service
+        sudo systemctl daemon-reload
+        sudo systemctl enable loki
+        sudo systemctl start loki
+      else
+        echo "sudo cp $loki_shell_base/config/loki.service /etc/systemd/system/loki.service"
+        echo "sudo systemctl daemon-reload"
+        echo "sudo systemctl enable loki"
+        echo "sudo systemctl start loki"
+        prompt "Copy these commands and run them when the script finishes."
+      fi
+    else
+      echo "This is as far as this script can take you, to run Loki run $loki_shell_base/.loki-shell/bin/loki -config.file=$loki_shell_base/.loki-shell/config/loki-binary-config.yaml"
+    fi
+  fi
+fi
+
+
 
 if [ $update_config -eq 2 ]; then
-  echo
-  ask "Do you want to update your shell configuration files?"
-  update_config=$?
+  # The script used to ask if you wanted to update shell files, I removed this so set this var to the value of "yes"
+  updated_config=1
+
+  default_host="http://localhost:4100"
+  loki_host=$(prompt_string "")
+  if [ -x "$loki_shell_base"/config/promtail-logging-config.yaml ]; then
+    prompt "Existing promtail config file found at $loki_shell_base/.loki-shell/config/promtail-logging-config.yaml\nFile will not be modified\n"
+  else
+    cp cfg-template/promtail-logging-config.yaml config/promtail-logging-config.yaml
+    sed -i "s|HOST|$loki_host|g" config/promtail-logging-config.yaml
+  fi
 fi
 echo
 for shell in $shells; do
-  [[ "$shell" = fish ]] && continue
   [ $shell = zsh ] && dest=${ZDOTDIR:-~}/.zshrc || dest=~/.bashrc
-  append_line $update_config "[ -f ${prefix}.${shell} ] && source ${prefix}.${shell}" "$dest" "${prefix}.${shell}"
+  append_line $update_config "# NOTE when changing the Loki URL, also remember to change the promtail config: ~/.loki-shell/config/promtail-logging-config.yaml\nexport LOKI_URL=\"$loki_host\""
+  append_line $update_config "[ -f ${prefix}/shell/loki-shell.${shell} ] && ${prefix}/shell/loki-shell.${shell}" "$dest" "${prefix}.${shell}"
 done
 
-if [ $key_bindings -eq 1 ] && [[ "$shells" =~ fish ]]; then
-  bind_file="${fish_dir}/functions/fish_user_key_bindings.fish"
-  if [ ! -e "$bind_file" ]; then
-    create_file "$bind_file" \
-      'function fish_user_key_bindings' \
-      '  fzf_key_bindings' \
-      'end'
-  else
-    append_line $update_config "fzf_key_bindings" "$bind_file"
-  fi
-fi
 
 if [ $update_config -eq 1 ]; then
   echo 'Finished. Restart your shell or reload config file.'
@@ -417,9 +367,7 @@ if [ $update_config -eq 1 ]; then
     echo
   fi
   [[ "$shells" =~ zsh ]]  && echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
-  [[ "$shells" =~ fish ]] && [ $key_bindings -eq 1 ] && echo '   fzf_key_bindings  # fish'
   echo
-  echo 'Use uninstall script to remove fzf.'
+  echo 'Use uninstall script to remove loki-shell.'
   echo
 fi
-echo 'For more information, see: https://github.com/junegunn/fzf'
